title: John Hios # your name (or website title) here
logo: "/images/DSC_0448_thumbnail.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist at Howden Group Ltd.
  <br><br>
  A Ph.D. qualified Mech & Aeronautical Engineer with 18+ years of experience
  in different engineering roles who branched out to the data space and 
  joined the Data Driven Advantage (DDA) team of Howden Group Ltd.
  <br><br>
  <a href="https://www.linkedin.com/in/johnhios/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
